apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: compra-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-compra-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70