server:
  port: 8081
spring:
  application:
    name: estoque
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  datasource:
    url: jdbc:mysql://10.0.0.186:3306/estoque?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: q1w2e3r4


#  server.error.include-stacktrace=never
#
#  spring.datasource.url = jdbc:mysql://10.0.0.186:3306/estoque?useTimezone=true&serverTimezone=UTC&sslMode=DISABLED&allowPublicKeyRetrieval=true
#  spring.datasource.username = root
#  spring.datasource.password = q1w2e3r4
#
#
#  spring.jpa.hibernate.ddl-auto = validate
#  spring.jpa.show-sql = true
#  spring.jpa.properties.hibernate.format_sql = true